### ISSUE TITLE
Trouble installing on new machine

### ISSUE THREAD

**Issue by ollie-art** [CapableRobot/CapableRobot_CircuitPython_USBHub_Bridge#5]
I was using my CapableRobotComponents USB hub on an old Windows 7 machine, and it's been running fine for over a year.
I now have to use it on a different PC, running Windows 10.  
I have followed the installation instructions on the page https://capablerobot.com/products/programmable-usb-hub/
I've also tried running the offline installer.

To start with, when I navigate to the 

`c:\User\username\Appdata\Roaming\Python\Python310\Scripts`

directory, and run 

`usbhub.exe id` 

it gave me an error "Entity not found".  This suggested to me that the driver may not have installed correctly.
I then realised that this new Windows 10 PC has been configured by IT so that I need to use an admin account to install certain software.   So I ran the command line as administrator and re-performed the installation.  I think I also ran the offline installer as admin, and when it asked whether just for me or all users, I installed for all users.  This puts the files in a different location: 

`c:\Program Files\Python310\Scripts`

Now if I run 

`usbhub.exe id` 

it returns the correct information, suggesting the installation has been more successful.  However, when I run the command

`usbhub.exe --disable-i2c power state --port 1 --on` 

I get a new Python error message:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\usbhub.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python310\lib\site-packages\capablerobot_usbhub\console.py", line 239, in main
    cli()
  File "C:\Program Files\Python310\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Python310\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Python310\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Python310\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Python310\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\capablerobot_usbhub\console.py", line 226, in state
    hub.power.enable(ports=port)
  File "C:\Program Files\Python310\lib\site-packages\capablerobot_usbhub\power.py", line 86, in enable
    self.hub.register_write(addr=self.control_register(port-1), buf=[0x81])
  File "C:\Program Files\Python310\lib\site-packages\capablerobot_usbhub\power.py", line 64, in control_register
    if self.hub.revision >= 2:
  File "C:\Program Files\Python310\lib\site-packages\capablerobot_usbhub\device.py", line 260, in revision
    self._revision = self._sku[1]
TypeError: 'NoneType' object is not subscriptable

Any help much appreciated.  Should I be installing as the admin?  For all users?  Anything else I've done wrong?

**Comment by ollie-art** [comment]
I've since done a fresh install with a new user account that is admin, and still getting the same result.

**Comment by ollie-art** [comment]
I looked back at the previous thread, and then I ran this:
`pip install git+https://github.com/CapableRobot/CapableRobot_USBHub_Driver`

Now I get a slightly different error when I run

`usbhub --disable-i2c power state --port 1 --on`

I get

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\usbhub.exe\__main__.py", line 7, in <module>
  File "C:\Users\Automated Test\AppData\Roaming\Python\Python310\site-packages\capablerobot_usbhub\console.py", line 237, in main
    cli()
  File "C:\Program Files\Python310\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Python310\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Python310\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Python310\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Python310\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Automated Test\AppData\Roaming\Python\Python310\site-packages\capablerobot_usbhub\console.py", line 224, in state
    hub.power.enable(ports=port)
  File "C:\Users\Automated Test\AppData\Roaming\Python\Python310\site-packages\capablerobot_usbhub\power.py", line 86, in enable
    self.hub.register_write(addr=self.control_register(port-1), buf=[0x81])
  File "C:\Users\Automated Test\AppData\Roaming\Python\Python310\site-packages\capablerobot_usbhub\power.py", line 64, in control_register
    if self.hub.revision >= 2:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

**Comment by ollie-art** [comment]
I don't know if it's relevant, but the hub shows up as "Microsoft XBox Controller Type S (COM7) in Device Manager.

**Comment by osterwood** [comment]
My apologies for the delayed response — and thank you for the detailed logs.  I suspect the issue here is that the wrong underlying usb driver is being used.  Do you run the `usbregister` command? If so, can you check with Zapotec that libusbk is associated with the VID/PID of the Hub?

https://zadig.akeo.ie/

Zadig can also be used to manually associate the Hub with the libusbk driver — it may be that the `usbregister` tool has some TBD issue with new Windows 10 installs.

**Comment by ollie-art** [comment]
I've found a workaround, this no longer affects me.

**Comment by ollie-art** [comment]
For reference, yes we played with Zadig and usbregister quite a bit, nothing seemed to work.

**Comment by osterwood** [comment]
@ollie-art I think the following commit fixes the issue: https://github.com/CapableRobot/CapableRobot_USBHub_Driver/commit/01d88db199adac57714674aa06c3a5ebb2b11d9f

It was a bug in the python host-side driver -- not the underlying USB driver assignment.  

We made a minor change in hardware interconnect between revision 1 and 2 of the Hub, and need to know about that change for power control to map correctly to the USB Hub ports.  When I2C is disabled, the only way to query Hub revision is via device descriptors or the deviceid register (0x3004).  But, older versions of the firmware did not set these alternate information paths up (that firmware assumes that the revision in the I2C EEPROM will always be accessible).

So, this revision comparison was failing.  The commit above changes the logic to assume revision 0 or revision 1 power control mapping when hub revision cannot be queried (which is only the case when I2C has been disabled, Hub firmware is old, and Hub hardware is revision 0 or 1).

**Comment by osterwood** [comment]
Again, my apologies for the delayed response to your issue.  Best regards, Chris

**Comment by ollie-art** [comment]
Hi Chris - many thanks for this information - I'll give it a go and see if I can get it working again :)
